current_model: xlm-roberta-large, timestamp: 1700696501
Traceback (most recent call last):
  File "/users/ob234/cpc_ob234/cpc-main/calc_emission_inference.py", line 214, in <module>
    main()
  File "/users/ob234/cpc_ob234/cpc-main/calc_emission_inference.py", line 205, in main
    query(pipe, task_type, tokenizer, input_data, model_name)
  File "/users/ob234/.local/lib/python3.10/site-packages/pyJoules/energy_meter.py", line 295, in wrapper_measure
    energy_meter.start(tag=func.__name__)
  File "/users/ob234/.local/lib/python3.10/site-packages/pyJoules/energy_meter.py", line 103, in start
    new_state = self._measure_new_state(tag)
  File "/users/ob234/.local/lib/python3.10/site-packages/pyJoules/energy_meter.py", line 79, in _measure_new_state
    values = [device.get_energy() for device in self.devices]
  File "/users/ob234/.local/lib/python3.10/site-packages/pyJoules/energy_meter.py", line 79, in <listcomp>
    values = [device.get_energy() for device in self.devices]
  File "/users/ob234/.local/lib/python3.10/site-packages/pyJoules/device/rapl_device.py", line 219, in get_energy
    energies = [self._read_energy_value(open(api_file_name, 'r')) for api_file_name in self._api_file_names]
  File "/users/ob234/.local/lib/python3.10/site-packages/pyJoules/device/rapl_device.py", line 219, in <listcomp>
    energies = [self._read_energy_value(open(api_file_name, 'r')) for api_file_name in self._api_file_names]
PermissionError: [Errno 13] Permission denied: '/sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj'
